

[owner]
name = "Tom Preston-Werner"
pseudo  = "Tommy"
int = 3
int2 = +100
simple = [3, 4]
real = 2.4
real2 = -22.4
real3 = +1.0
# breaks it int3 = 100_100

# for the database
[database]
server = "192.168.1.1" # quoted string
ports = [8001, 8001, 8002] # array
connection_max = 5000 # integer
enabled = true  # boolean

[servers]
arr1 = [ 1, 2, 3 ]
arr2 = [ "red", 
"yellow",                   "green" ]
arr3 = [ [ 1,
 2 ],
 [
3,
 4,
 5]
 ]
arr4 = [ "all", 'strings', """are the same""", '''type''']
arr5 = [ [ 1, 2 ], ["a", "b", "c"] ]


[misc]
"computer" = """ this 
	   is a multi line 
	   string """

[someField]
key = '''this is a sample message'''
key2 = ''' this is a multi
line
	sample
message'''