[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1" # quoted string
ports = [ 8001, 8001, 8002 ] # array
connection_max = 5000 # integer
enabled = true  # boolean

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

  [servers.zeta]
  ip = ["10.0.0.2", "10.0.0.9"] 


# Array corner cases 
# Mismatched array type. 
[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]